/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    BirdHouse: typeof import('./src/components/BirdHouse.vue')['default']
    CalendarWidget: typeof import('./src/components/CalendarWidget.vue')['default']
    CalendarWidgetDayItem: typeof import('./src/components/CalendarWidgetDayItem.vue')['default']
    CalendarWidgetMonthNavigator: typeof import('./src/components/CalendarWidgetMonthNavigator.vue')['default']
    CalendarWidgetWeekDays: typeof import('./src/components/CalendarWidgetWeekDays.vue')['default']
    ContactsForm: typeof import('./src/components/steps/ContactsForm.vue')['default']
    LocationInfoForm: typeof import('./src/components/steps/LocationInfoForm.vue')['default']
    ProfileInfoForm: typeof import('./src/components/steps/ProfileInfoForm.vue')['default']
    RegistrationForm: typeof import('./src/components/steps/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheAlert: typeof import('./src/components/TheAlert.vue')['default']
    TheButton: typeof import('./src/components/TheButton.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheDatePicker: typeof import('./src/components/TheDatePicker.vue')['default']
    TheField: typeof import('./src/components/TheField.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheForm: typeof import('./src/components/TheForm.vue')['default']
    TheIcon: typeof import('./src/components/TheIcon.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    ThePaginator: typeof import('./src/components/ThePaginator.vue')['default']
    TheSelect: typeof import('./src/components/TheSelect.vue')['default']
    TheStepper: typeof import('./src/components/TheStepper.vue')['default']
    TheTabs: typeof import('./src/components/TheTabs.vue')['default']
    UiIcon: typeof import('./src/components/UiIcon.vue')['default']
  }
}
